### ISSUE TITLE
fix failing `struct` case

### ISSUE THREAD

**Issue by noot** [ChainSafe/serde-bin-prot#30]
currently, this test case fails: https://github.com/janestreet/bin_prot/blob/master/test/non_integers_repr.ml#L747 

the struct and test are defined in `tests/struct.rs`:
```
#[derive(Serialize, Deserialize, Debug, PartialEq)]
struct C {
    y: CInner,
    z: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, PartialEq)]
struct CInner {}
```

```
    let c0 = C {
        y: CInner {},
        z: None,
    };

    let mut c0_expected = vec![0x00, 0x00, 0x01, 0x01];
    c0_expected.reverse();
```

the test output is:
```
thread 'test_serialize_structs' panicked at 'assertion failed: `(left == right)`
  left: `[1, 1, 0, 0]`, // expected
 right: `[0]`', tests/struct.rs:100:13 // actual
```

would be good to double check that the rust struct is the same as the OCaml struct, and if so, then this case needs to be fixed.

**Comment by willemolding** [comment]
I think some clarification can be found here https://docs.w3cub.com/ocaml/inlinerecords.html

Inline records do not correspond to structs but rather to sum/enum types. This explains the `0x01` as these are the bytes that indicate which enum variant to use. See inline records defined in the original test https://github.com/janestreet/bin_prot/blob/6c45b4249fc2c3a19574c4c788e2d296cae7fc30/test/non_integers_repr.ml#L463

The `0x00`s encode the unit types used in the variants.

In this case I think the fix is to rewrite CInner as an enum rather than a struct and we should be able to get the same output

**Comment by mmacedoeu** [comment]
The root cause is that inline records looks like some fancy constructor that is ocaml only and don't have a 1:1 map with any native Rust type and it also comes with extra bytes when encoding/decoding. So first at all I would recommend to not use some specific to one one language if you want this to be portable. You can get the same output and each way will come with it's own pro and cons regarding ergonomics, readability and maintainability:

1. Strip extra bytes and put it back later - This way you use plain Struct and code will be strong with ergonomics, readability and maintainability;
2. Use nested enums - This way each extra byte is implicit encoded into enum variant, it is somewhat compact as you don't need explicit extra field but your code will be full of rust 'match' expressions and more verbose to read and maintain;
3. Use structs with a dummy placeholder field, combined with other inner struct or enum - This way you need to walk into inner fields everywhere but don't need to use 'match', less verbose but still using compounding types to represent the inline record;
4. Use two representations - Use 2 or 3 for encoding/decoding steps and them implements rust Into trait to plain Struct so in this process you will strip and restore the extras bytes like in 1 but could make this less error prone and get best of both worlds.

**Comment by willemolding** [comment]
I don't know if I agree with you there. Inline records in OCaml map exactly to Rust enum struct variants

```ocaml
 type t =
   | Point of {width: int; mutable x: float; mutable y: float} (* this is the inline record *)
   | Other
```
is equivalent to 

```rust
enum t = {
    Point {width: i32, x: f32, y: f32}, // this is the inline record equivalent, a struct variant
    Other.
}
```
It is important to note that neither of these can exist except in the context of an enum. If they are not in an enum they are just structs/records. This explains the extra bytes since the encodings for enum variants are always prefixed by the variant index (0x00 for Point, 0x01 for Other).
