### ISSUE TITLE
Bug in array serialization

### ISSUE THREAD

**Issue by creativcoder** [ChainSafe/serde-bin-prot#31]
While porting the [array test cases](https://github.com/janestreet/bin_prot/blob/master/test/non_integers_repr.ml#L725), it was found that serde dispatches array serialization calls to serialize_tuple. serialize_tuple does not write the number of elements as the first byte as Nat0. This should be simple fix:

Code: https://github.com/ChainSafe/serde-bin-prot/blob/41e800f7dd2262ecfe30559a2c8f495306c68cbd/src/ser.rs#L205

**Comment by willemolding** [comment]
I don't think this is the correct fix. OCaml tuples serialized to bin-prot do not write the number of elements since they are fixed length and the type captures the information of the length (https://github.com/janestreet/bin_prot#tuples-and-records).

According to the specification, OCaml list and arrays do need to write out their length but not tuples. Hopefuly serde is flexible enough to allow us to do this. I think it will be though

**Comment by creativcoder** [comment]
Yeah, i figured from the other test cases failing. I also wonder why the array test case has the first byte which seems like it's the number of elements https://github.com/janestreet/bin_prot/blob/master/test/non_integers_repr.ml#L722

**Comment by creativcoder** [comment]
Either we need to covert the arrays to `vec!` or we need to customize the Serialize impl: https://docs.rs/serde/1.0.126/src/serde/ser/impls.rs.html#130-138 which would result in conflicting trait implementations. The 3rd way is for us to provide a wrapper `BinProt` type, with a From impl (to create `BinProt` instances from native rust types) on which we then implement Serializer.
